apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "happy-queue"
  namespace: "default"
  labels:
    app: "happy-queue"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "happy-queue"
  template:
    metadata:
      labels:
        app: "happy-queue"
    spec:
      containers:
        - name: "happy-queue"
          image: "gcr.io/upheld-apricot-267218/happy-queue:v19"
          env:
            - name: JASYPT_ENCRYPTOR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jasypt-encryptor-password
                  key: password
            - name: CLOUD_SQL_IP
              value: "10.38.192.3"
